import { useState } from 'react';
import { useQuery, useMutation } from '@tanstack/react-query';
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { 
  Table, 
  TableBody, 
  TableCell, 
  TableHead, 
  TableHeader, 
  TableRow 
} from "@/components/ui/table";
import { 
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { 
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue 
} from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { 
  FileText, 
  Settings, 
  Play, 
  Pause, 
  RefreshCw, 
  Calendar,
  Eye,
  Edit,
  Trash2,
  Plus,
  Bot,
  Clock,
  TrendingUp
} from "lucide-react";
import { useToast } from '@/hooks/use-toast';
import { apiRequest } from '@/lib/queryClient';
import { queryClient } from '@/lib/queryClient';
import { format } from 'date-fns';
import { ru } from 'date-fns/locale';

interface BlogArticle {
  id: string;
  title: string;
  slug: string;
  content: string;
  excerpt?: string;
  category: string;
  tags: string[];
  status: string;
  publishedAt?: string;
  generatedBy?: string;
  authorName?: string;
  readingTime?: number;
  isAutoGenerated: boolean;
  featured: boolean;
  viewCount: number;
  createdAt: string;
  updatedAt: string;
}

interface BlogGenerationSettings {
  id: string;
  isEnabled: boolean;
  frequency: string;
  maxArticlesPerDay: number;
  topics: string[];
  contentLength: string;
  targetAudience: string;
  tone: string;
  language: string;
  lastGeneration?: string;
  nextGeneration?: string;
  totalGenerated: number;
}

interface SchedulerStatus {
  isRunning: boolean;
  lastRun: string | null;
  nextRun: string | null;
  totalGenerated: number;
  errors: number;
}

export default function AdminBlog() {
  const { toast } = useToast();
  const [selectedArticle, setSelectedArticle] = useState<BlogArticle | null>(null);
  const [isCreating, setIsCreating] = useState(false);

  // Queries
  const { data: articles, isLoading: articlesLoading } = useQuery({
    queryKey: ['/api/admin/blog/articles'],
  });

  const { data: settings, isLoading: settingsLoading } = useQuery({
    queryKey: ['/api/admin/blog/settings'],
  });

  const { data: schedulerStatus, isLoading: statusLoading } = useQuery({
    queryKey: ['/api/admin/blog/scheduler/status'],
    refetchInterval: 30000, // Обновляем каждые 30 секунд
  });

  // Mutations
  const generateMutation = useMutation({
    mutationFn: async () => {
      const response = await apiRequest('POST', '/api/admin/blog/generate');
      return await response.json();
    },
    onSuccess: () => {
      toast({
        title: 'Генерация запущена',
        description: 'Новые статьи будут созданы в ближайшее время',
      });
      queryClient.invalidateQueries({ queryKey: ['/api/admin/blog/articles'] });
      queryClient.invalidateQueries({ queryKey: ['/api/admin/blog/scheduler/status'] });
    },
    onError: () => {
      toast({
        title: 'Ошибка генерации',
        description: 'Не удалось запустить генерацию статей',
        variant: 'destructive',
      });
    },
  });

  const updateSettingsMutation = useMutation({
    mutationFn: async (newSettings: Partial<BlogGenerationSettings>) => {
      const response = await apiRequest('PATCH', '/api/admin/blog/settings', newSettings);
      return await response.json();
    },
    onSuccess: () => {
      toast({
        title: 'Настройки сохранены',
        description: 'Настройки генерации блога обновлены',
      });
      queryClient.invalidateQueries({ queryKey: ['/api/admin/blog/settings'] });
    },
  });

  const deleteArticleMutation = useMutation({
    mutationFn: async (articleId: string) => {
      const response = await apiRequest('DELETE', `/api/admin/blog/articles/${articleId}`);
      return await response.json();
    },
    onSuccess: () => {
      toast({
        title: 'Статья удалена',
        description: 'Статья успешно удалена из блога',
      });
      queryClient.invalidateQueries({ queryKey: ['/api/admin/blog/articles'] });
    },
  });

  const publishArticleMutation = useMutation({
    mutationFn: async ({ articleId, status }: { articleId: string; status: string }) => {
      const response = await apiRequest('PATCH', `/api/admin/blog/articles/${articleId}`, { status });
      return await response.json();
    },
    onSuccess: () => {
      toast({
        title: 'Статья обновлена',
        description: 'Статус статьи изменен',
      });
      queryClient.invalidateQueries({ queryKey: ['/api/admin/blog/articles'] });
    },
  });

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'published': return 'bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200';
      case 'draft': return 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-200';
      case 'archived': return 'bg-gray-100 text-gray-800 dark:bg-gray-900 dark:text-gray-200';
      default: return 'bg-gray-100 text-gray-800 dark:bg-gray-900 dark:text-gray-200';
    }
  };

  const getStatusText = (status: string) => {
    switch (status) {
      case 'published': return 'Опубликовано';
      case 'draft': return 'Черновик';
      case 'archived': return 'Архив';
      default: return status;
    }
  };

  if (articlesLoading || settingsLoading || statusLoading) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
      </div>
    );
  }

  return (
    <div className="space-y-6 p-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold" data-testid="text-admin-blog-title">
            Управление блогом
          </h1>
          <p className="text-muted-foreground">
            Генерация и управление статьями блога ResCrub
          </p>
        </div>
        <div className="flex gap-2">
          <Button
            onClick={() => generateMutation.mutate()}
            disabled={generateMutation.isPending}
            data-testid="button-generate-article"
          >
            <Bot className="h-4 w-4 mr-2" />
            {generateMutation.isPending ? 'Генерация...' : 'Сгенерировать статью'}
          </Button>
          <Button variant="outline" data-testid="button-create-article">
            <Plus className="h-4 w-4 mr-2" />
            Создать статью
          </Button>
        </div>
      </div>

      {/* Stats Cards */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Всего статей</CardTitle>
            <FileText className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{(articles as any)?.length || 0}</div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Опубликовано</CardTitle>
            <TrendingUp className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">
              {(articles as any)?.filter((a: BlogArticle) => a.status === 'published').length || 0}
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Сгенерировано ИИ</CardTitle>
            <Bot className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{(schedulerStatus as any)?.totalGenerated || 0}</div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Статус планировщика</CardTitle>
            <Clock className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="flex items-center gap-2">
              <div className={`h-2 w-2 rounded-full ${(schedulerStatus as any)?.isRunning ? 'bg-green-500' : 'bg-red-500'}`} />
              <span className="text-sm">{(schedulerStatus as any)?.isRunning ? 'Активен' : 'Остановлен'}</span>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Main Content */}
      <Tabs defaultValue="articles" className="space-y-4">
        <TabsList>
          <TabsTrigger value="articles">Статьи</TabsTrigger>
          <TabsTrigger value="settings">Настройки генерации</TabsTrigger>
          <TabsTrigger value="scheduler">Планировщик</TabsTrigger>
        </TabsList>

        {/* Articles Tab */}
        <TabsContent value="articles" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Статьи блога</CardTitle>
            </CardHeader>
            <CardContent>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Заголовок</TableHead>
                    <TableHead>Категория</TableHead>
                    <TableHead>Статус</TableHead>
                    <TableHead>Автор</TableHead>
                    <TableHead>Дата создания</TableHead>
                    <TableHead>Просмотры</TableHead>
                    <TableHead className="text-right">Действия</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {(articles as any)?.map((article: BlogArticle) => (
                    <TableRow key={article.id}>
                      <TableCell className="font-medium">
                        <div className="flex items-center gap-2">
                          {article.featured && (
                            <Badge variant="secondary" className="text-xs">TOP</Badge>
                          )}
                          {article.isAutoGenerated && (
                            <Bot className="h-3 w-3 text-muted-foreground" />
                          )}
                          <span className="truncate max-w-[300px]">{article.title}</span>
                        </div>
                      </TableCell>
                      <TableCell>
                        <Badge variant="outline">{article.category}</Badge>
                      </TableCell>
                      <TableCell>
                        <Badge className={getStatusColor(article.status)}>
                          {getStatusText(article.status)}
                        </Badge>
                      </TableCell>
                      <TableCell className="text-sm text-muted-foreground">
                        {article.authorName || 'ResCrub AI'}
                      </TableCell>
                      <TableCell className="text-sm text-muted-foreground">
                        {format(new Date(article.createdAt), 'dd.MM.yyyy HH:mm', { locale: ru })}
                      </TableCell>
                      <TableCell className="text-sm">
                        {article.viewCount || 0}
                      </TableCell>
                      <TableCell className="text-right">
                        <div className="flex justify-end gap-1">
                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => window.open(`/blog/${article.slug}`, '_blank')}
                            data-testid={`button-view-${article.id}`}
                          >
                            <Eye className="h-4 w-4" />
                          </Button>
                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => setSelectedArticle(article)}
                            data-testid={`button-edit-${article.id}`}
                          >
                            <Edit className="h-4 w-4" />
                          </Button>
                          {article.status === 'draft' && (
                            <Button
                              variant="ghost"
                              size="sm"
                              onClick={() => publishArticleMutation.mutate({ 
                                articleId: article.id, 
                                status: 'published' 
                              })}
                              data-testid={`button-publish-${article.id}`}
                            >
                              <Play className="h-4 w-4" />
                            </Button>
                          )}
                          <AlertDialog>
                            <AlertDialogTrigger asChild>
                              <Button
                                variant="ghost"
                                size="sm"
                                data-testid={`button-delete-${article.id}`}
                              >
                                <Trash2 className="h-4 w-4" />
                              </Button>
                            </AlertDialogTrigger>
                            <AlertDialogContent>
                              <AlertDialogHeader>
                                <AlertDialogTitle>Удалить статью?</AlertDialogTitle>
                                <AlertDialogDescription>
                                  Это действие нельзя отменить. Статья будет удалена навсегда.
                                </AlertDialogDescription>
                              </AlertDialogHeader>
                              <AlertDialogFooter>
                                <AlertDialogCancel>Отмена</AlertDialogCancel>
                                <AlertDialogAction
                                  onClick={() => deleteArticleMutation.mutate(article.id)}
                                  className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
                                >
                                  Удалить
                                </AlertDialogAction>
                              </AlertDialogFooter>
                            </AlertDialogContent>
                          </AlertDialog>
                        </div>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>

              {!(articles as any)?.length && (
                <div className="text-center py-8 text-muted-foreground">
                  <FileText className="h-12 w-12 mx-auto mb-4 opacity-50" />
                  <p>Статьи не найдены</p>
                  <p className="text-sm">Создайте первую статью или запустите автогенерацию</p>
                </div>
              )}
            </CardContent>
          </Card>
        </TabsContent>

        {/* Settings Tab */}
        <TabsContent value="settings" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Настройки автогенерации</CardTitle>
              <p className="text-sm text-muted-foreground">
                Управление параметрами автоматической генерации статей
              </p>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="flex items-center justify-between">
                <div className="space-y-0.5">
                  <Label>Автогенерация включена</Label>
                  <p className="text-sm text-muted-foreground">
                    Автоматически создавать новые статьи по расписанию
                  </p>
                </div>
                <Switch
                  checked={(settings as any)?.isEnabled || false}
                  onCheckedChange={(checked) =>
                    updateSettingsMutation.mutate({ isEnabled: checked })
                  }
                  data-testid="switch-auto-generation"
                />
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label>Частота генерации</Label>
                  <Select
                    value={(settings as any)?.frequency || 'daily'}
                    onValueChange={(value) =>
                      updateSettingsMutation.mutate({ frequency: value })
                    }
                  >
                    <SelectTrigger data-testid="select-frequency">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="hourly">Каждый час</SelectItem>
                      <SelectItem value="daily">Ежедневно</SelectItem>
                      <SelectItem value="weekly">Еженедельно</SelectItem>
                    </SelectContent>
                  </Select>
                </div>

                <div className="space-y-2">
                  <Label>Максимум статей в день</Label>
                  <Input
                    type="number"
                    min="1"
                    max="10"
                    value={(settings as any)?.maxArticlesPerDay || 3}
                    onChange={(e) =>
                      updateSettingsMutation.mutate({ 
                        maxArticlesPerDay: parseInt(e.target.value) 
                      })
                    }
                    data-testid="input-max-articles"
                  />
                </div>
              </div>

              <div className="space-y-2">
                <Label>Темы для генерации</Label>
                <Textarea
                  placeholder="Введите темы через запятую..."
                  value={(settings as any)?.topics?.join(', ') || ''}
                  onChange={(e) =>
                    updateSettingsMutation.mutate({ 
                      topics: e.target.value.split(',').map(t => t.trim()).filter(Boolean)
                    })
                  }
                  data-testid="textarea-topics"
                />
                <p className="text-sm text-muted-foreground">
                  Разделяйте темы запятыми. Например: защита данных, 152-ФЗ, кибербезопасность
                </p>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        {/* Scheduler Tab */}
        <TabsContent value="scheduler" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Статус планировщика</CardTitle>
              <p className="text-sm text-muted-foreground">
                Мониторинг и управление автоматической генерацией
              </p>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="space-y-4">
                  <div className="flex items-center justify-between p-4 border rounded-lg">
                    <div>
                      <p className="font-medium">Статус</p>
                      <p className="text-sm text-muted-foreground">
                        {(schedulerStatus as any)?.isRunning ? 'Планировщик активен' : 'Планировщик остановлен'}
                      </p>
                    </div>
                    <div className={`h-3 w-3 rounded-full ${(schedulerStatus as any)?.isRunning ? 'bg-green-500' : 'bg-red-500'}`} />
                  </div>

                  <div className="p-4 border rounded-lg">
                    <p className="font-medium">Последний запуск</p>
                    <p className="text-sm text-muted-foreground">
                      {(schedulerStatus as any)?.lastRun 
                        ? format(new Date((schedulerStatus as any).lastRun), 'dd.MM.yyyy HH:mm', { locale: ru })
                        : 'Никогда'
                      }
                    </p>
                  </div>
                </div>

                <div className="space-y-4">
                  <div className="p-4 border rounded-lg">
                    <p className="font-medium">Следующий запуск</p>
                    <p className="text-sm text-muted-foreground">
                      {(schedulerStatus as any)?.nextRun 
                        ? format(new Date((schedulerStatus as any).nextRun), 'dd.MM.yyyy HH:mm', { locale: ru })
                        : 'Не запланирован'
                      }
                    </p>
                  </div>

                  <div className="p-4 border rounded-lg">
                    <p className="font-medium">Ошибки</p>
                    <p className="text-sm text-muted-foreground">
                      {(schedulerStatus as any)?.errors || 0} ошибок
                    </p>
                  </div>
                </div>
              </div>

              <div className="flex gap-2">
                <Button
                  onClick={() => generateMutation.mutate()}
                  disabled={generateMutation.isPending}
                  data-testid="button-force-generation"
                >
                  <RefreshCw className="h-4 w-4 mr-2" />
                  {generateMutation.isPending ? 'Генерация...' : 'Запустить сейчас'}
                </Button>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}