import { BlogGeneratorService } from "./blog-generator";
import { IStorage } from "./storage";

export interface SchedulerStatus {
  isRunning: boolean;
  lastRun: Date | null;
  nextRun: Date | null;
  totalGenerated: number;
  errors: number;
}

export class BlogScheduler {
  private intervalId: NodeJS.Timeout | null = null;
  private isRunning = false;
  private status: SchedulerStatus = {
    isRunning: false,
    lastRun: null,
    nextRun: null,
    totalGenerated: 0,
    errors: 0
  };

  constructor(
    private blogGenerator: BlogGeneratorService,
    private storage: IStorage,
    private checkIntervalMinutes: number = 30 // Проверяем каждые 30 минут
  ) {}

  /**
   * Запускает планировщик задач
   */
  start(): void {
    if (this.intervalId) {
      console.log("📅 Blog scheduler is already running");
      return;
    }

    console.log(`🚀 Starting blog scheduler (checking every ${this.checkIntervalMinutes} minutes)`);
    
    this.isRunning = true;
    this.status.isRunning = true;
    
    // Запускаем первую проверку через 1 минуту после старта
    setTimeout(() => this.runScheduledCheck(), 60 * 1000);
    
    // Устанавливаем регулярные проверки
    this.intervalId = setInterval(() => {
      this.runScheduledCheck();
    }, this.checkIntervalMinutes * 60 * 1000);

    console.log("✅ Blog scheduler started successfully");
  }

  /**
   * Останавливает планировщик задач
   */
  stop(): void {
    if (this.intervalId) {
      clearInterval(this.intervalId);
      this.intervalId = null;
    }
    
    this.isRunning = false;
    this.status.isRunning = false;
    this.status.nextRun = null;
    
    console.log("⏹️ Blog scheduler stopped");
  }

  /**
   * Получает текущий статус планировщика
   */
  getStatus(): SchedulerStatus {
    return { ...this.status };
  }

  /**
   * Принудительно запускает генерацию (игнорируя расписание)
   */
  async forceGeneration(): Promise<{
    articlesGenerated: number;
    nextGenerationAt: Date | null;
    message: string;
  }> {
    console.log("🔥 Force generation requested");
    
    try {
      const result = await this.blogGenerator.runScheduledGeneration();
      
      this.status.lastRun = new Date();
      this.status.totalGenerated += result.articlesGenerated;
      this.status.nextRun = result.nextGenerationAt;
      
      if (result.articlesGenerated > 0) {
        console.log(`✅ Force generation completed: ${result.articlesGenerated} articles`);
      } else {
        console.log(`ℹ️ Force generation completed: ${result.message}`);
      }
      
      return result;
    } catch (error) {
      this.status.errors++;
      console.error("❌ Force generation failed:", error);
      throw error;
    }
  }

  /**
   * Выполняет запланированную проверку и генерацию
   */
  private async runScheduledCheck(): Promise<void> {
    if (!this.isRunning) {
      return;
    }

    console.log("🔍 Running scheduled blog generation check...");

    try {
      const result = await this.blogGenerator.runScheduledGeneration();
      
      this.status.lastRun = new Date();
      this.status.nextRun = result.nextGenerationAt;
      
      if (result.articlesGenerated > 0) {
        this.status.totalGenerated += result.articlesGenerated;
        console.log(`📰 Scheduled generation successful: ${result.articlesGenerated} articles created`);
        
        // Уведомляем в логи для мониторинга
        console.log(`📊 Total articles generated by scheduler: ${this.status.totalGenerated}`);
      } else {
        console.log(`⏰ Scheduled check completed: ${result.message}`);
      }
      
    } catch (error) {
      this.status.errors++;
      console.error("❌ Scheduled generation failed:", error);
      
      // Не останавливаем планировщик из-за ошибки, продолжаем работу
      console.log("🔄 Scheduler will continue running despite the error");
    }
  }

  /**
   * Получает подробную информацию о настройках генерации
   */
  async getGenerationSettings(): Promise<{
    enabled: boolean;
    frequency: string;
    maxArticlesPerDay: number;
    nextScheduledRun: Date | null;
    articlesToday: number;
  }> {
    try {
      const settings = await this.storage.getBlogGenerationSettings();
      
      // Подсчитываем статьи за сегодня
      const today = new Date();
      today.setHours(0, 0, 0, 0);
      
      const todayArticles = await this.storage.getAllBlogArticles({
        status: "published",
        limit: 200 // Увеличиваем лимит для точного подсчета
      });
      
      const articlesToday = todayArticles.filter(article => 
        article.publishedAt && article.publishedAt >= today
      ).length;

      return {
        enabled: settings?.isEnabled ?? false,
        frequency: settings?.frequency ?? "daily", 
        maxArticlesPerDay: settings?.maxArticlesPerDay ?? 3,
        nextScheduledRun: settings?.nextGenerationAt ?? null,
        articlesToday
      };
      
    } catch (error) {
      console.error("❌ Failed to get generation settings:", error);
      return {
        enabled: false,
        frequency: "daily",
        maxArticlesPerDay: 3,
        nextScheduledRun: null,
        articlesToday: 0
      };
    }
  }

  /**
   * Обновляет настройки генерации
   */
  async updateGenerationSettings(updates: {
    enabled?: boolean;
    frequency?: string;
    maxArticlesPerDay?: number;
  }): Promise<void> {
    try {
      await this.storage.updateBlogGenerationSettings({
        isEnabled: updates.enabled,
        frequency: updates.frequency,
        maxArticlesPerDay: updates.maxArticlesPerDay,
        updatedAt: new Date()
      });
      
      console.log("⚙️ Generation settings updated:", updates);
    } catch (error) {
      console.error("❌ Failed to update generation settings:", error);
      throw error;
    }
  }

  /**
   * Получает статистику работы планировщика
   */
  getSchedulerStats(): {
    status: SchedulerStatus;
    uptime: string;
    checkInterval: number;
    errorRate: number;
  } {
    const uptime = this.status.lastRun 
      ? `${Math.round((Date.now() - this.status.lastRun.getTime()) / (1000 * 60))} минут назад`
      : "Еще не запускался";
      
    const errorRate = this.status.totalGenerated > 0 
      ? Math.round((this.status.errors / (this.status.totalGenerated + this.status.errors)) * 100)
      : 0;

    return {
      status: this.getStatus(),
      uptime,
      checkInterval: this.checkIntervalMinutes,
      errorRate
    };
  }
}